import Header from './Header';
import Head from 'next/head';
import { ReactChild } from 'react';
import styles from './layout.module.css';

interface LayoutProps {
    children: ReactChild,
    title ?: string
}

export default function Layout({title, children}: LayoutProps){
    return(
        <>
        <div className={styles.container}>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by BrainBattle" />
                <link rel="icon" href='/icon.png' />
            </Head>
    
            <main className={styles.main}>
                <Header />
                {children}
            </main>
        </div>
        </>
    )
}