import Header from './Header';
import Head from 'next/head';
import Image from 'next/image';
import { ReactChild } from 'react';
import styles from '../../../styles/layout.module.css';
import background from '../../../public/image/back3.jpg'

interface LayoutProps {
    children: ReactChild,
    title ?: string
}

export default function Layout({title, children}: LayoutProps){
    return(
        <>
        <div className="p-0">
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by BrainBattle" />
                <link rel="icon" href='/icon.png' />
            </Head>
    
            <main className="min-h-screen flex-1 flex-col flex">
                <Header />
                {children}
            </main>
        </div>
        </>
    )
}